on:
  schedule:
    - cron: "* */1 * * *"

name: bot

jobs:
  run-bot-job:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.3'
      - name: Query dependencies
        run: |
          install.packages('remotes')
           saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
           writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}
      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      - name: Install system dependencies
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')
      - name: Install the package from the current repository
        run: |
          remotes::install_local(force = TRUE)
        shell: Rscript {0}
      - name: Run bot scripts
        env:
          RTWEET_APP: ${{ secrets.RTWEET_APP }}
          RTWEET_CONSUMER_KEY: ${{ secrets.RTWEET_CONSUMER_KEY }}
          RTWEET_CONSUMER_SECRET: ${{ secrets.RTWEET_CONSUMER_SECRET }}
          RTWEET_ACCESS_TOKEN: ${{ secrets.RTWEET_ACCESS_TOKEN }}
          RTWEET_ACCESS_SECRET: ${{ secrets.RTWEET_ACCESS_SECRET }}
        run: |
          
          library("cannabisjobsbot")
          library("dplyr")
          library("glue")
          library("lubridate")
          library("purrr")
          library("rtweet")
          
          invisible(create_token(
            app = Sys.getenv("RTWEET_APP"),
            consumer_key = Sys.getenv("RTWEET_CONSUMER_KEY"),
            consumer_secret = Sys.getenv("RTWEET_CONSUMER_SECRET"),
            access_token = Sys.getenv("RTWEET_ACCESS_TOKEN"),
            access_secret = Sys.getenv("RTWEET_ACCESS_SECRET")
          ))
          
          cannabis_jobs <- get_jobs() %>% 
            mutate(msg = glue(
              "{trimws(job)} position at the {department} department at {company} {twitter} ({location}) ",
              "#CannabisJobs #CannaBiz #CannabisIndustry ",
              "{url}"
            )) %>% 
            filter(updated_at >= now() - hours(1))
          message(glue(
            "To post {nrow(cannabis_jobs)} jobs: ",
            "{paste(table(cannabis_jobs$company), names(table(cannabis_jobs$company)), collapse = '; ')}"
          ))
          invisible(map(cannabis_jobs$msg, post_tweet))
        shell: Rscript {0}
